import type { InventoryItem } from './types';

export const ITEM_TYPES: Record<InventoryItem['category'], string> = {
  weapon: 'Armas',
  armor: 'Armaduras e escudos',
  ammunition: 'Munições',
  potion: 'Poções',
  consumable: 'Consumíveis',
  tool: 'Ferramentas e instrumentos',
  focus: 'Focos de conjuração',
  container: 'Recipientes',
  gear: 'Equipamentos de aventura',
  treasure: 'Tesouros',
  magic: 'Itens mágicos',
  item: 'Outros itens',
};
export interface ItemUse {
  kind: 'healing' | 'damage' | 'utility';
  dice: string;
  range: number;
  consumed: boolean;
  note: string;
  special?: 'stabilize' | 'antitoxin';
}
export type CatalogItem = Omit<InventoryItem, 'id'> & { catalog_id: string; use?: ItemUse };
const base = (
  catalog_id: string,
  name: string,
  category: InventoryItem['category'],
  weight: number,
  cost_gp: number,
  notes = '',
): CatalogItem => ({
  catalog_id,
  name,
  category,
  quantity: 1,
  weight,
  cost_gp,
  equipped: false,
  notes,
});
const weapon = (
  id: string,
  name: string,
  type: 'simple' | 'martial',
  damage: string,
  weight: number,
  cost: number,
  properties: string[] = [],
  range = 1.5,
  versatile?: string,
  ammo?: string,
): CatalogItem => ({
  ...base(id, name, 'weapon', weight, cost),
  weapon_type: type,
  damage,
  properties,
  notes: properties.join(', '),
  weapon_mode: properties.includes('distância') ? 'ranged' : 'melee',
  weapon_range: range,
  versatile_damage: versatile,
  ammunition: ammo,
});
const armor = (
  id: string,
  name: string,
  type: InventoryItem['armor_type'],
  ac: number,
  weight: number,
  cost: number,
  note = '',
): CatalogItem => ({
  ...base(id, name, 'armor', weight, cost, note),
  armor_type: type,
  armor_base: ac,
});
const healing = (
  id: string,
  name: string,
  dice: string,
  rarity: string,
  cost: number,
): CatalogItem => ({
  ...base(id, name, 'potion', 0.25, cost, `Uma ação para beber ou administrar; cura ${dice} PV.`),
  rarity,
  use: {
    kind: 'healing',
    dice,
    range: 1.5,
    consumed: true,
    note: 'Beber ou administrar a uma criatura ao alcance de toque. Não acrescenta atributo de conjuração.',
  },
});

export const ITEM_CATALOG: CatalogItem[] = [
  weapon('club', 'Clava', 'simple', '1d4 concussão', 1, 0.1, ['leve']),
  weapon('dagger', 'Adaga', 'simple', '1d4 perfurante', 0.5, 2, ['acuidade', 'leve', 'arremesso']),
  weapon('greatclub', 'Clava grande', 'simple', '1d8 concussão', 5, 0.2, ['duas mãos']),
  weapon('handaxe', 'Machadinha', 'simple', '1d6 cortante', 1, 5, ['leve', 'arremesso']),
  weapon('javelin', 'Azagaia', 'simple', '1d6 perfurante', 1, 0.5, ['arremesso']),
  weapon('light-hammer', 'Martelo leve', 'simple', '1d4 concussão', 1, 2, ['leve', 'arremesso']),
  weapon('mace', 'Maça', 'simple', '1d6 concussão', 2, 5),
  weapon('quarterstaff', 'Bordão', 'simple', '1d6 concussão', 2, 0.2, ['versátil'], 1.5, '1d8'),
  weapon('sickle', 'Foice', 'simple', '1d4 cortante', 1, 1, ['leve']),
  weapon(
    'spear',
    'Lança',
    'simple',
    '1d6 perfurante',
    1.5,
    1,
    ['arremesso', 'versátil'],
    1.5,
    '1d8',
  ),
  weapon(
    'light-crossbow',
    'Besta leve',
    'simple',
    '1d8 perfurante',
    2.5,
    25,
    ['distância', 'munição', 'recarga', 'duas mãos'],
    24,
    undefined,
    'bolt',
  ),
  weapon(
    'dart',
    'Dardo',
    'simple',
    '1d4 perfurante',
    0.1,
    0.05,
    ['distância', 'acuidade', 'arremesso'],
    6,
  ),
  weapon(
    'shortbow',
    'Arco curto',
    'simple',
    '1d6 perfurante',
    1,
    25,
    ['distância', 'munição', 'duas mãos'],
    24,
    undefined,
    'arrow',
  ),
  weapon(
    'sling',
    'Funda',
    'simple',
    '1d4 concussão',
    0,
    0.1,
    ['distância', 'munição'],
    9,
    undefined,
    'bullet',
  ),
  weapon(
    'battleaxe',
    'Machado de batalha',
    'martial',
    '1d8 cortante',
    2,
    10,
    ['versátil'],
    1.5,
    '1d10',
  ),
  weapon('flail', 'Mangual', 'martial', '1d8 concussão', 1, 10),
  weapon(
    'glaive',
    'Glaive',
    'martial',
    '1d10 cortante',
    3,
    20,
    ['pesada', 'duas mãos', 'alcance'],
    3,
  ),
  weapon('greataxe', 'Machado grande', 'martial', '1d12 cortante', 3.5, 30, [
    'pesada',
    'duas mãos',
  ]),
  weapon('greatsword', 'Espada grande', 'martial', '2d6 cortante', 3, 50, ['pesada', 'duas mãos']),
  weapon(
    'halberd',
    'Alabarda',
    'martial',
    '1d10 cortante',
    3,
    20,
    ['pesada', 'duas mãos', 'alcance'],
    3,
  ),
  weapon(
    'lance',
    'Lança de cavalaria',
    'martial',
    '1d12 perfurante',
    3,
    10,
    ['alcance', 'especial'],
    3,
  ),
  weapon(
    'longsword',
    'Espada longa',
    'martial',
    '1d8 cortante',
    1.5,
    15,
    ['versátil'],
    1.5,
    '1d10',
  ),
  weapon('maul', 'Malho', 'martial', '2d6 concussão', 5, 10, ['pesada', 'duas mãos']),
  weapon('morningstar', 'Maça-estrela', 'martial', '1d8 perfurante', 2, 15),
  weapon(
    'pike',
    'Pique',
    'martial',
    '1d10 perfurante',
    9,
    5,
    ['pesada', 'duas mãos', 'alcance'],
    3,
  ),
  weapon('rapier', 'Rapieira', 'martial', '1d8 perfurante', 1, 25, ['acuidade']),
  weapon('scimitar', 'Cimitarra', 'martial', '1d6 cortante', 1.5, 25, ['acuidade', 'leve']),
  weapon('shortsword', 'Espada curta', 'martial', '1d6 perfurante', 1, 10, ['acuidade', 'leve']),
  weapon(
    'trident',
    'Tridente',
    'martial',
    '1d6 perfurante',
    2,
    5,
    ['arremesso', 'versátil'],
    1.5,
    '1d8',
  ),
  weapon('war-pick', 'Picareta de guerra', 'martial', '1d8 perfurante', 1, 5),
  weapon(
    'warhammer',
    'Martelo de guerra',
    'martial',
    '1d8 concussão',
    1,
    15,
    ['versátil'],
    1.5,
    '1d10',
  ),
  weapon('whip', 'Chicote', 'martial', '1d4 cortante', 1.5, 2, ['acuidade', 'alcance'], 3),
  weapon(
    'blowgun',
    'Zarabatana',
    'martial',
    '1 perfurante',
    0.5,
    10,
    ['distância', 'munição', 'recarga'],
    7.5,
    undefined,
    'needle',
  ),
  weapon(
    'hand-crossbow',
    'Besta de mão',
    'martial',
    '1d6 perfurante',
    1.5,
    75,
    ['distância', 'leve', 'munição', 'recarga'],
    9,
    undefined,
    'bolt',
  ),
  weapon(
    'heavy-crossbow',
    'Besta pesada',
    'martial',
    '1d10 perfurante',
    9,
    50,
    ['distância', 'pesada', 'munição', 'recarga', 'duas mãos'],
    30,
    undefined,
    'bolt',
  ),
  weapon(
    'longbow',
    'Arco longo',
    'martial',
    '1d8 perfurante',
    1,
    50,
    ['distância', 'pesada', 'munição', 'duas mãos'],
    45,
    undefined,
    'arrow',
  ),
  weapon('net', 'Rede', 'martial', '', 1.5, 1, ['distância', 'especial', 'arremesso'], 1.5),
  armor('padded', 'Armadura acolchoada', 'light', 11, 4, 5, 'Desvantagem em Furtividade'),
  armor('leather', 'Armadura de couro', 'light', 11, 5, 10),
  armor('studded-leather', 'Couro batido', 'light', 12, 6.5, 45),
  armor('hide', 'Armadura de peles', 'medium', 12, 6, 10),
  armor('chain-shirt', 'Cota de malha parcial', 'medium', 13, 10, 50),
  armor('scale-mail', 'Brunea', 'medium', 14, 22.5, 50, 'Desvantagem em Furtividade'),
  armor('breastplate', 'Peitoral', 'medium', 14, 10, 400),
  armor('half-plate', 'Meia armadura', 'medium', 15, 20, 750, 'Desvantagem em Furtividade'),
  armor('ring-mail', 'Cota de anéis', 'heavy', 14, 20, 30, 'Desvantagem em Furtividade'),
  armor(
    'chain-mail',
    'Cota de malha',
    'heavy',
    16,
    27.5,
    75,
    'Força 13; desvantagem em Furtividade',
  ),
  armor(
    'splint',
    'Armadura segmentada',
    'heavy',
    17,
    30,
    200,
    'Força 15; desvantagem em Furtividade',
  ),
  armor(
    'plate',
    'Armadura de placas',
    'heavy',
    18,
    32.5,
    1500,
    'Força 15; desvantagem em Furtividade',
  ),
  armor('shield', 'Escudo', 'shield', 2, 3, 10),
  ...[
    ['arrow', 'Flechas', 0.05, 0.05],
    ['bolt', 'Virotes', 0.075, 0.05],
    ['bullet', 'Balas de funda', 0.025, 0.002],
    ['needle', 'Agulhas de zarabatana', 0.005, 0.02],
  ].map(([id, name, weight, cost]) => ({
    ...base(
      String(id),
      String(name),
      'ammunition',
      Number(weight),
      Number(cost),
      'Quantidade e preço por unidade; o disparo aprovado consome 1.',
    ),
    ammunition: String(id),
    quantity: id === 'needle' ? 50 : 20,
  })),
  healing('potion-healing', 'Poção de cura', '2d4+2', 'Comum', 50),
  healing('potion-greater-healing', 'Poção de cura maior', '4d4+4', 'Incomum', 0),
  healing('potion-superior-healing', 'Poção de cura superior', '8d4+8', 'Rara', 0),
  healing('potion-supreme-healing', 'Poção de cura suprema', '10d4+20', 'Muito rara', 0),
  {
    ...base('acid', 'Ácido (frasco)', 'consumable', 0.5, 25),
    use: {
      kind: 'damage',
      dice: '2d6',
      range: 6,
      consumed: true,
      note: 'Ataque à distância com arma improvisada; o mestre decide o acerto.',
    },
  },
  {
    ...base('holy-water', 'Água benta (frasco)', 'consumable', 0.5, 25),
    use: {
      kind: 'damage',
      dice: '2d6',
      range: 6,
      consumed: true,
      note: 'Dano radiante somente contra ínferos ou mortos-vivos; o mestre verifica o tipo do alvo.',
    },
  },
  {
    ...base('antitoxin', 'Antitoxina', 'consumable', 0, 50),
    use: {
      kind: 'utility',
      dice: '',
      range: 1.5,
      consumed: true,
      special: 'antitoxin',
      note: 'Vantagem contra veneno durante 1 hora; não beneficia construtos ou mortos-vivos. O mestre aplica a vantagem.',
    },
  },
  {
    ...base('healers-kit', 'Kit de primeiros socorros', 'tool', 1.5, 5),
    charges: 10,
    use: {
      kind: 'utility',
      dice: '',
      range: 1.5,
      consumed: false,
      special: 'stabilize',
      note: 'Uma ação e 1 dos 10 usos estabilizam uma criatura a 0 PV, sem restaurar PV.',
    },
  },
  ...[
    ['backpack', 'Mochila', 'container', 2.5, 2, 'Capacidade aproximada: 15 kg.'],
    ['pouch', 'Bolsa', 'container', 0.5, 0.5, ''],
    ['chest', 'Baú', 'container', 12.5, 5, ''],
    ['quiver', 'Aljava', 'container', 0.5, 1, 'Até 20 flechas.'],
    ['waterskin', 'Odre', 'container', 2.5, 0.2, ''],
    ['rope', 'Corda de cânhamo', 'gear', 5, 1, '15 metros.'],
    ['silk-rope', 'Corda de seda', 'gear', 2.5, 10, '15 metros.'],
    ['bedroll', 'Saco de dormir', 'gear', 3.5, 1, ''],
    ['tinderbox', 'Caixa de fogo', 'gear', 0.5, 0.5, 'Uma ação para acender combustível exposto.'],
    [
      'lantern',
      'Lanterna coberta',
      'gear',
      1,
      5,
      'Luz plena 9 m; penumbra por mais 9 m. Consome óleo.',
    ],
    ['torch', 'Tocha', 'gear', 0.5, 0.01, 'Luz plena 6 m; penumbra por mais 6 m, durante 1 hora.'],
    ['rations', 'Rações (dia)', 'consumable', 1, 0.5, 'Alimentação de 1 dia.'],
    [
      'oil',
      'Óleo (frasco)',
      'consumable',
      0.5,
      0.1,
      'Combustível; efeitos de fogo dependem do mestre.',
    ],
    ['clothes', 'Roupas comuns', 'gear', 1.5, 0.5, ''],
    ['book', 'Livro', 'gear', 2.5, 25, ''],
    ['spellbook', 'Grimório', 'gear', 1.5, 50, 'Registro das magias de mago.'],
    [
      'component-pouch',
      'Bolsa de componentes',
      'focus',
      1,
      25,
      'Substitui materiais sem custo e não consumidos pela magia.',
    ],
    [
      'arcane-focus',
      'Foco arcano',
      'focus',
      0.5,
      10,
      'Para mago, bruxo ou feiticeiro; não substitui materiais consumidos ou com custo.',
    ],
    [
      'druidic-focus',
      'Foco druídico',
      'focus',
      0,
      1,
      'Para druida; não substitui materiais consumidos ou com custo.',
    ],
    [
      'holy-symbol',
      'Símbolo sagrado',
      'focus',
      0.5,
      5,
      'Para clérigo ou paladino; pode estar no escudo.',
    ],
    [
      'thieves-tools',
      'Ferramentas de ladrão',
      'tool',
      0.5,
      25,
      'Abrir fechaduras e desarmar armadilhas; proficiência conforme a ficha.',
    ],
    [
      'artisan-tools',
      'Ferramentas de artesão',
      'tool',
      2.5,
      10,
      'Escolha o ofício nas observações.',
    ],
    ['herbalism-kit', 'Kit de herbalismo', 'tool', 1.5, 5, ''],
    ['disguise-kit', 'Kit de disfarce', 'tool', 1.5, 25, ''],
    ['forgery-kit', 'Kit de falsificação', 'tool', 2.5, 15, ''],
    ['lute', 'Alaúde', 'tool', 1, 35, 'Instrumento musical; pode ser foco para bardo.'],
    ['flute', 'Flauta', 'tool', 0.5, 2, 'Instrumento musical; pode ser foco para bardo.'],
  ].map(([id, name, category, weight, cost, notes]) =>
    base(
      String(id),
      String(name),
      category as InventoryItem['category'],
      Number(weight),
      Number(cost),
      String(notes),
    ),
  ),
];
export function catalogItem(item: InventoryItem) {
  return ITEM_CATALOG.find((e) => e.catalog_id === item.catalog_id);
}
export function normalizeItem(item: InventoryItem): InventoryItem {
  const entry =
    catalogItem(item) ??
    (!item.catalog_id ? ITEM_CATALOG.find((e) => e.name === item.name) : undefined);
  if (!entry) return item.quantity === 0 ? { ...item, equipped: false } : item;
  const { use: _use, ...data } = entry;
  return {
    ...data,
    ...item,
    catalog_id: entry.catalog_id,
    category: entry.category,
    equipped: item.quantity === 0 ? false : item.equipped,
  };
}
export function itemUse(item: InventoryItem): ItemUse | undefined {
  const entry = catalogItem(item);
  if (
    !entry?.use ||
    item.quantity < 1 ||
    (entry.charges && (item.charges_used ?? 0) >= entry.charges)
  )
    return;
  return entry.use;
}
export function equipItem(inventory: InventoryItem[], id: string, equipped: boolean) {
  const selected = inventory.find((i) => i.id === id);
  return inventory.map((i) =>
    i.id === id
      ? { ...i, equipped }
      : equipped &&
          selected?.category === 'armor' &&
          i.category === 'armor' &&
          (selected.armor_type === 'shield' ? i.armor_type === 'shield' : i.armor_type !== 'shield')
        ? { ...i, equipped: false }
        : i,
  );
}
